apiVersion: 1

datasources:
  - name: GridSense TimescaleDB
    uid: gridsense-timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: gridsense
    user: postgres
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: postgres
